### ISSUE TITLE
Import error for voxelwise_correlation

### ISSUE THREAD

**Issue by PKhush** [Parietal-INRIA/fmralign#84]
Hi, I'm trying to run[ this](https://parietal-inria.github.io/fmralign-docs/auto_examples/plot_pairwise_alignment.html#sphx-glr-auto-examples-plot-pairwise-alignment-py) example tutorial and I get `ImportError: cannot import name 'voxelwise_correlation' from 'fmralign._utils'`. Has this function been removed/moved/renamed? I couldn't find it in the package code.

Thanks for your help.

**Comment by bthirion** [comment]
Hi,
Thx for reporting.
Running the code locally, I don't get the error (I use the version from the Github repo). Which version are you using ?
Best,

**Comment by pbarbarant** [comment]
It appears that the deployed doc on github pages is outdated, in the meantime, @PKhush you can run locally `/examples/plot_pairwise_alignment.py` which seems up-to-date with our latest changes.


@bthirion our `.github/workflows/doc-build.yml` does not contain a deployment action, maybe appending the following job might do the trick (I'll have to check exactly)
```
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
```
